apiVersion: rbac.authorization.k8s.io/v1beta1   #쿠버네티스 최신버전에서는 promethues cluster role 작성시 v1beta1 대신 v1 으로 작성해야 오류가 안남
kind: ClusterRole
metadata:
  name: prometheus
  namespace: monitoring
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/proxy
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1  #쿠버네티스 최신버전에서는 promethues cluster role 작성시 v1beta1 대신 v1 으로 작성해야 오류가 안남
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: default
  namespace: monitoring
